"""Change status to string

Revision ID: afc91c2f88be
Revises: 5deb501b5e16
Create Date: 2026-07-13 13:23:48.276180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afc91c2f88be'
down_revision: Union[str, Sequence[str], None] = '5deb501b5e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'status',
               existing_type=postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', name='requeststatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', name='requeststatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
